[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://coffeejob.netlify.app/*"
  to = "https://coffeejob.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://coffeejob.netlify.app/*"
  to = "https://coffeejob.io/:splat"
  status = 301
  force = true